package dz.edu.univconstantine2.ntic.als.model;

public enum NotificationType {
    /** Auto-generated by ProactiveRemediationService when a learner fails a quiz */
    REMEDIATION,
    /** Auto-generated by RecommendationService based on chat history */
    RECOMMENDATION
}
